# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os .environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, PlayfairMainWindow):
        PlayfairMainWindow.setObjectName("PlayfairMainWindow")
        PlayfairMainWindow.resize(705, 550)
        self.centralwidget = QtWidgets.QWidget(PlayfairMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(200, 10, 300, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.plain_text_label = QtWidgets.QLabel(self.centralwidget)
        self.plain_text_label.setGeometry(QtCore.QRect(20, 120, 80, 13))
        self.plain_text_label.setObjectName("plain_text_label")
        self.key_label = QtWidgets.QLabel(self.centralwidget)
        self.key_label.setGeometry(QtCore.QRect(20, 190, 80, 13))
        self.key_label.setObjectName("key_label")
        self.cipher_text_label = QtWidgets.QLabel(self.centralwidget)
        self.cipher_text_label.setGeometry(QtCore.QRect(20, 260, 80, 16))
        self.cipher_text_label.setObjectName("cipher_text_label")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(190, 340, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(400, 340, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(100, 120, 461, 61))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(100, 260, 461, 61))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(100, 190, 461, 41))
        self.txt_key.setObjectName("txt_key")
        self.label_student_info = QtWidgets.QLabel(self.centralwidget)
        self.label_student_info.setGeometry(QtCore.QRect(150, 60, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_student_info.setFont(font)
        self.label_student_info.setObjectName("label_student_info")
        self.label_matrix = QtWidgets.QLabel(self.centralwidget)
        self.label_matrix.setGeometry(QtCore.QRect(20, 390, 80, 16))
        self.label_matrix.setObjectName("label_matrix")
        self.txt_playfair_matrix = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_playfair_matrix.setGeometry(QtCore.QRect(100, 390, 461, 120))
        self.txt_playfair_matrix.setReadOnly(True)
        self.txt_playfair_matrix.setObjectName("txt_playfair_matrix")
        PlayfairMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlayfairMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menubar.setObjectName("menubar")
        PlayfairMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlayfairMainWindow)
        self.statusbar.setObjectName("statusbar")
        PlayfairMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlayfairMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayfairMainWindow)

    def retranslateUi(self, PlayfairMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayfairMainWindow.setWindowTitle(_translate("PlayfairMainWindow", "Playfair Cipher"))
        self.label_title.setText(_translate("PlayfairMainWindow", "PLAYFAIR CIPHER"))
        self.plain_text_label.setText(_translate("PlayfairMainWindow", "Plain text:"))
        self.key_label.setText(_translate("PlayfairMainWindow", "Key:"))
        self.cipher_text_label.setText(_translate("PlayfairMainWindow", "Cipher text:"))
        self.btn_encrypt.setText(_translate("PlayfairMainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("PlayfairMainWindow", "Decrypt"))
        self.label_student_info.setText(_translate("PlayfairMainWindow", "TRẦN SỶ SƠN LÂM - 2280601697"))
        self.label_matrix.setText(_translate("PlayfairMainWindow", "Playfair Matrix:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlayfairMainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(PlayfairMainWindow)
    PlayfairMainWindow.show()
    sys.exit(app.exec_())
