# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os .environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, VigenereMainWindow):
        VigenereMainWindow.setObjectName("VigenereMainWindow")
        VigenereMainWindow.resize(705, 457)
        self.centralwidget = QtWidgets.QWidget(VigenereMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(200, 10, 300, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.plain_text_label = QtWidgets.QLabel(self.centralwidget)
        self.plain_text_label.setGeometry(QtCore.QRect(20, 120, 80, 13))
        self.plain_text_label.setObjectName("plain_text_label")
        self.key_label = QtWidgets.QLabel(self.centralwidget)
        self.key_label.setGeometry(QtCore.QRect(20, 190, 80, 13))
        self.key_label.setObjectName("key_label")
        self.cipher_text_label = QtWidgets.QLabel(self.centralwidget)
        self.cipher_text_label.setGeometry(QtCore.QRect(20, 240, 80, 16))
        self.cipher_text_label.setObjectName("cipher_text_label")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(190, 330, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(400, 330, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(100, 120, 461, 61))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(100, 240, 461, 61))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(100, 190, 461, 41))
        self.txt_key.setObjectName("txt_key")
        self.label_student_info = QtWidgets.QLabel(self.centralwidget)
        self.label_student_info.setGeometry(QtCore.QRect(150, 60, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_student_info.setFont(font)
        self.label_student_info.setObjectName("label_student_info")
        VigenereMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VigenereMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menubar.setObjectName("menubar")
        VigenereMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VigenereMainWindow)
        self.statusbar.setObjectName("statusbar")
        VigenereMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VigenereMainWindow)
        QtCore.QMetaObject.connectSlotsByName(VigenereMainWindow)

    def retranslateUi(self, VigenereMainWindow):
        _translate = QtCore.QCoreApplication.translate
        VigenereMainWindow.setWindowTitle(_translate("VigenereMainWindow", "Vigenere Cipher"))
        self.label_title.setText(_translate("VigenereMainWindow", "VIGENERE CIPHER"))
        self.plain_text_label.setText(_translate("VigenereMainWindow", "Plain text:"))
        self.key_label.setText(_translate("VigenereMainWindow", "Key:"))
        self.cipher_text_label.setText(_translate("VigenereMainWindow", "Cipher text:"))
        self.btn_encrypt.setText(_translate("VigenereMainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("VigenereMainWindow", "Decrypt"))
        self.label_student_info.setText(_translate("VigenereMainWindow", "TRẦN SỶ SƠN LÂM - 2280601697"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VigenereMainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(VigenereMainWindow)
    VigenereMainWindow.show()
    sys.exit(app.exec_())
